### ISSUE TITLE
java.lang.IllegalArgumentException: Class com.google.cloud.solutions.autotokenize.encryptors.AesEcbStringValueTokenizer does extend ValueTokenizerFactory

### ISSUE THREAD

**Issue by jaymilagroso-globe** [GoogleCloudPlatform/auto-data-tokenize#47]
**Error**
```sh
Exception in thread "main" java.lang.IllegalArgumentException: Error creating encryptionValueFactory
        at com.google.cloud.solutions.autotokenize.pipeline.EncryptionPipeline$EncryptingPipelineFactory.buildValueTokenizerFactory(EncryptionPipeline.java:332)
        at com.google.cloud.solutions.autotokenize.pipeline.EncryptionPipeline$EncryptingPipelineFactory.tinkEncryption(EncryptionPipeline.java:284)
        at com.google.cloud.solutions.autotokenize.pipeline.EncryptionPipeline$EncryptingPipelineFactory.makeEncryptingSteps(EncryptionPipeline.java:271)
        at com.google.cloud.solutions.autotokenize.pipeline.EncryptionPipeline.applyReadAndEncryptionSteps(EncryptionPipeline.java:156)
        at com.google.cloud.solutions.autotokenize.pipeline.EncryptionPipeline.run(EncryptionPipeline.java:123)
        at com.google.cloud.solutions.autotokenize.pipeline.EncryptionPipeline.main(EncryptionPipeline.java:85)
Caused by: java.lang.IllegalArgumentException: Class com.google.cloud.solutions.autotokenize.encryptors.AesEcbStringValueTokenizer does extend ValueTokenizerFactory
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:220)
        at com.google.cloud.solutions.autotokenize.pipeline.EncryptionPipeline$EncryptingPipelineFactory.buildValueTokenizerFactory(EncryptionPipeline.java:292)
```

**Steps to replicate**

Clone latest version
```sh
git clone https://github.com/GoogleCloudPlatform/auto-data-tokenize.git
```

Update and source set set_variables.sh file
```sh
vi set_variables.sh
source set_variables.sh
```

Compile
```sh
./gradlew clean buildNeeded shadowJar
```

Sample and Identify
```sh
sample_and_identify_pipeline --project="my-project" \
--region="asia-southeast1" \
--runner="DataflowRunner" \
--serviceAccount="my-dlp-runner@my-project.iam.gserviceaccount.com" \
--gcpTempLocation="gs://my-bucket/temp" \
--stagingLocation="gs://my-bucket/staging" \
--tempLocation="gs://my-bucket/bqtemp" \
--workerMachineType="n1-standard-1" \
--sampleSize=1000 \
--sourceType="CSV_FILE" \
--inputPattern="gs://my-bucket/data/*" \
--reportLocation="gs://my-bucket/dlp_report/" \
--usePublicIps=false \
--subnetwork="https://www.googleapis.com/compute/v1/projects/my-network/regions/asia-southeast1/subnetworks/my-subnet-prod"
```

Tokenize
```sh
tokenize_pipeline --project="my-project" \
--region="asia-southeast1" \
--runner="DataflowRunner" \
--tempLocation="gs://my-bucket/temp" \
--workerMachineType="n1-standard-1" \
--sourceType="CSV_FILE" \
--csvHeaders="mobile_number,created_at" \
--inputPattern="gs://my-bucket/data/*" \
--outputBigQueryTable="my-project:my_dataset.my_table" \
--tokenizeColumns="$.mobile_number" \
--valueTokenizerFactoryFullClassName="com.google.cloud.solutions.autotokenize.encryptors.AesEcbStringValueTokenizer$AesEcbValueTokenizerFactory" \
--keyMaterial="projects/123456789012/secrets/my_encryption_key/versions/1" \
--keyMaterialType=GCP_SECRET_KEY \
--usePublicIps=false \
--subnetwork="https://www.googleapis.com/compute/v1/projects/my-network/regions/asia-southeast1/subnetworks/my-subnet-prod"
```

**Comment by anantdamle** [comment]
Now you can launch the pipeline with following updated options:

```
tokenize_pipeline --project="my-project" \
--region="asia-southeast1" \
--runner="DataflowRunner" \
--tempLocation="gs://my-bucket/temp" \
--workerMachineType="n1-standard-1" \
--sourceType="CSV_FILE" \
--csvHeaders="mobile_number,created_at" \
--inputPattern="gs://my-bucket/data/*" \
--outputBigQueryTable="my-project:my_dataset.my_table" \
--tokenizeColumns="$.mobile_number" \
--valueTokenizerFactoryFullClassName="com.google.cloud.solutions.autotokenize.encryptors.AesEcbValueTokenizerFactory" \
--keyMaterial="projects/123456789012/secrets/my_encryption_key/versions/1" \
--keyMaterialType=GCP_SECRET_KEY \
--usePublicIps=false \
--subnetwork="https://www.googleapis.com/compute/v1/projects/my-network/regions/asia-southeast1/subnetworks/my-subnet-prod"
```
